### ISSUE TITLE
怎么刷新界面的

### ISSUE THREAD

**Issue by liushunyu** [iSpring/GamePlane#3]
您好，想问一下是怎么实现实时的刷新绘制界面的吖，是开了线程吗？

**Comment by iSpring** [comment]
你好，没有额外开其他线程。

我实现了一个GameView，继承自View类，在GameView不断调用postInvalidate()方法，这样就驱动着GameView不断重绘，可以参考这里的代码：
https://github.com/iSpring/GamePlane/blob/master/app/src/main/java/com/ispring/gameplane/game/GameView.java#L214

**Comment by liushunyu** [comment]
我明白是用postInvalidate()方法来重绘了，但我在代码中找不到是在哪一块不断【实时】调用了这个函数，你是设置了什么监听器来实时调用postInvalidate()这个函数的，还是说怎么实现的吖，具体是哪个代码不断调用了呢（注：我想知道的是“不断调用”这个过程是在哪里执行的，而不是哪个函数调用了postInvalidate()），不知道我说清楚了吗

**Comment by iSpring** [comment]
postInvalidate()方法会触发View执行onDraw()方法，所以会出现如下调用过程：
onDraw() -> 用Canvas绘图，绘图完成后调用postInvalidate()方法 -> 然后再次触发onDraw() -> ...

可以调试跟一下代码就清楚了
